### ISSUE TITLE
Themes don't work

### ISSUE THREAD

**Issue by oaim** [sund/ProtonmailThemes#1]
None of these themes work for me. They mess up the interface, the left panel is all white.

**Comment by sund** [comment]
These are 1.X version themes. Not intended to work in v2.0.

**Comment by oaim** [comment]
I see. So this repository is kinda useless :/ I found some cool themes here though: https://github.com/csalmeida/protonmail-themes/tree/master/Themes/v2.0 :)

**Comment by sund** [comment]
Yeah. I found these after they introduced Themes in v1.X and after v2.0 came out, themes seemed to take a back seat.

This is more for archive purposes only.
